// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvIEHTqEms5rUjDZusxqYUDzupZ4ihwiw',
    appId: '1:766027156556:web:e66912c8e9fd3fc2b078e9',
    messagingSenderId: '766027156556',
    projectId: 'tp-flutter-firebase-75229',
    authDomain: 'tp-flutter-firebase-75229.firebaseapp.com',
    storageBucket: 'tp-flutter-firebase-75229.firebasestorage.app',
    measurementId: 'G-0TY27V7XPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD51Ei1STVy7eoc-nCVh7PiqbcyAlaTGM8',
    appId: '1:766027156556:android:951a6be803a28741b078e9',
    messagingSenderId: '766027156556',
    projectId: 'tp-flutter-firebase-75229',
    storageBucket: 'tp-flutter-firebase-75229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPps6_KAgoBg7r3alqo_6JFVPd_8Js_J8',
    appId: '1:766027156556:ios:51077cac75c93300b078e9',
    messagingSenderId: '766027156556',
    projectId: 'tp-flutter-firebase-75229',
    storageBucket: 'tp-flutter-firebase-75229.firebasestorage.app',
    iosBundleId: 'com.example.tpGilbertoPires',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPps6_KAgoBg7r3alqo_6JFVPd_8Js_J8',
    appId: '1:766027156556:ios:51077cac75c93300b078e9',
    messagingSenderId: '766027156556',
    projectId: 'tp-flutter-firebase-75229',
    storageBucket: 'tp-flutter-firebase-75229.firebasestorage.app',
    iosBundleId: 'com.example.tpGilbertoPires',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvIEHTqEms5rUjDZusxqYUDzupZ4ihwiw',
    appId: '1:766027156556:web:f6d9d4a5c5266f1bb078e9',
    messagingSenderId: '766027156556',
    projectId: 'tp-flutter-firebase-75229',
    authDomain: 'tp-flutter-firebase-75229.firebaseapp.com',
    storageBucket: 'tp-flutter-firebase-75229.firebasestorage.app',
    measurementId: 'G-MJE4Q5HVHB',
  );
}
